- name: Update .bashrc
  register: update_bashrc
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    block: "{{ lookup('file', '{{ playbook_dir }}/roles/default/files/.bashrc') }}"
    marker: "# {mark} HARLEYS-DOTFILES MANAGED BLOCK - Update .bashrc"
    insertbefore: EOF
    create: yes
- name: Debug update_bashrc
  ansible.builtin.debug:
    msg: "{{ update_bashrc }}"

- name: Update .bash_harley
  register: update_bash_harley
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.bash_harley"
    block: "{{ lookup('file', '{{ playbook_dir }}/roles/default/files/.bash_harley') }}"
    marker: "# {mark} HARLEYS-DOTFILES MANAGED BLOCK - Update .bash_harley"
    insertafter: EOF
    create: yes
- name: Debug update_bash_harley
  ansible.builtin.debug:
    msg: "{{ update_bash_harley }}"
#- name: Update .bash_harley for Debian
#  register: update_bash_profile_debian
#  blockinfile:
#    dest: "{{ ansible_env.HOME }}/.bash_harley"
#    block: "{{ lookup('file', '{{ playbook_dir }}/roles/default/files/.bash_harley.debian') }}"
#    marker: "# {mark} HARLEYS-DOTFILES MANAGED BLOCK - Update .bash_harley for Debian"
#    insertafter: EOF
#    create: yes
#  when:
#    - ansible_distribution|string == 'Debian'
#- name: Debug update_bash_profile_debian
#  ansible.builtin.debug:
#    msg: "{{ update_bash_profile_debian }}"

- name: Source .bashrc
  register: source_bashrc
  shell: source ~/.bashrc
  args:
    executable: /bin/bash
- name: Debug source_bashrc
  ansible.builtin.debug:
    msg: "{{ source_bashrc }}"
